version: 2.1
orbs:
  cypress: cypress-io/cypress@1.13.0
  snyk: snyk/snyk@0.0.8
jobs:
  lint:
    executor: cypress/base-12-6-0
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  jest:
    executor: cypress/base-12-6-0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Jest Tests and convert coverage
          command: |
           yarn jest:test --coverage
           ./cc-test-reporter format-coverage coverage/lcov.info -t lcov -o ./codeclimate.jest.json
      - persist_to_workspace:
          root: ~/
          paths:
            - ./codeclimate.jest.json

  combine-coverage:
    executor: cypress/base-12-6-0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Combine Tests Reports
          command: |
            ./cc-test-reporter format-coverage cypress-coverage/lcov.info -t lcov -o ./codeclimate.cypress.json
            ./cc-test-reporter sum-coverage ./codeclimate.*.json -p 2 -o ./codeclimate.total.json
            ./cc-test-reporter upload-coverage -i ./codeclimate.total.json --debug

workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress/base-12-6-0
          yarn: true
          post-install:
            - run:
                name: Setup Code Climate test-reporter
                command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
                  ./cc-test-reporter before-build
          
      - lint:
          requires: 
            - cypress/install
      - jest:
          requires: 
            - cypress/install
      - combine-coverage:
          requires: 
            - cypress/e2e
            - jest
      - cypress/run:
          executor: cypress/base-12-6-0
          name: cypress/e2e
          yarn: true
          requires: 
            - cypress/install
          start: yarn start
          wait-on: 'http-get://localhost:3000'
          post-steps:
            - store_artifacts:
                path: cypress-coverage
           