version: 2.1
executors:
  my-executor:
    docker:
      - image: cypress/base:12.6.0
    working_directory:  ~/project/

orbs:
  cypress: cypress-io/cypress@1.13.0
  snyk: snyk/snyk@0.0.8
jobs:
  lint:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project/
      - run: yarn lint
  jest:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project/
      - run: yarn jest:test --coverage
  combine-coverage:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project/
      - run:
          name: Run LMS_Music Tests
          command: |
            ./cc-test-reporter before-build
            yarn report:combined
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  build:
    jobs:
      - cypress/install:
          executor: my-executor
          yarn: true
          post-install:
            - run:
                name: Setup Code Climate test-reporter
                command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
          
      - lint:
          requires: 
            - cypress/install
      - jest:
          requires: 
            - cypress/install
      - combine-coverage:
          requires: 
            - cypress/run
            - jest
      - cypress/run:
          executor: my-executor
          # run all tests
          start: yarn start
          wait-on: 'http-get://localhost:3000'
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: cypress-coverage